### ISSUE TITLE
Plank low-py

### ISSUE THREAD

**Issue by alexreevesy** [alessiospuriomancini/cosmopower#19]
Dear all, 

Do you already have an implementation of the Planck low ell bins? If not I have added the planck-low py (lognorm bins from https://github.com/heatherprince/planck-low-py) into the tf likelihood you have for Planck lite high ell TTTEEE by rewriting the functions in tf format and allowing them to take multiple Cl inputs if you would be interested in me sharing. 

Best wishes, 

Alex

**Comment by dpiras** [comment]
I'm going to close this @alexreevesy, and get back to you in case we need those data. Feel free to also re-open this issue if needed!
