### ISSUE TITLE
Please speed me up!

### ISSUE THREAD

**Issue by Sebastian-Belkner** [alessiospuriomancini/cosmopower#2]
Hi guys,
I was on the brink of installing CLASS when I stumbled upon your paper yesterday.

Would appreciate using your pretrained NN for the spectra coming out of [this](https://github.com/Sebastian-Belkner/component_separation) (and eventually [this](https://github.com/Sebastian-Belkner/cmb_skypatch)). I hope early accessing people doesn't cause you too much troubles.

**Comment by alessiospuriomancini** [comment]
Hi Sebastian, thanks for your interest in `CosmoPower`.
Not a problem at all - I will be in touch by email with you to share the code
