### ISSUE TITLE
New tensorflow version breaks restoring from pickle

### ISSUE THREAD

**Issue by itrharrison** [alessiospuriomancini/cosmopower#22]
The recent new version of tensorflow ([2.14.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.14.0)) moves (or removes? I can't actually find the functions in the new version) the `tensorflow.python.training.tracking` sub-module.

This seems to break restoring networks from pickle files:
```
(Pdb) tf.__version__
'2.14.0'
(Pdb) filename
'/-----/CosmoPower/CP_paper/CMB/cmb_TT_NN'
(Pdb) pickle.load(open(filename + ".pkl", 'rb'))
*** ModuleNotFoundError: No module named 'tensorflow.python.training.tracking'
```

I guess the dependency could be pinned `tensorflow<2.14.0`.

**Comment by dpiras** [comment]
Hi @itrharrison, thank you for flagging this! Could you confirm restoring from pickle files works correctly with `tensorflow<2.14.0`?

I will search for a fix, in case I agree we should update the TF dependency as you say.

**Comment by dpiras** [comment]
I can reproduce the problem with `tensorflow==2.14.0`, and confirm everything works as expected with e.g. ``tensorflow==2.13.0`. Looking into it now!

**Comment by dpiras** [comment]
The `tracking` module seems to be gone in `2.14`, and it's not indicated explicitly in the release notes. 

![image](https://github.com/alessiospuriomancini/cosmopower/assets/25639122/b556398a-0f89-4664-bc02-582205255416)

I would suggest using `2.13` (or below) for now, and I can open an issue on the [TF GitHub page](https://github.com/tensorflow/tensorflow/issues), unless you are already planning to do it @itrharrison?

If they do not plan to fix this, we should specify `< 2.14` in the requirements, as you suggested.

**Comment by itrharrison** [comment]
Issue away! I'm not sure if the pickle restore is their problem or not(?), but it seems wrong that the removal of `tracking` isn't in the release notes.

**Comment by dpiras** [comment]
Agreed! Issue opened [here](https://github.com/tensorflow/tensorflow/issues/62210), let's see what they say

**Comment by dpiras** [comment]
Based on https://github.com/tensorflow/tensorflow/issues/62210, they moved the module to [`tensorflow.python.trackable`](https://github.com/tensorflow/tensorflow/tree/r2.14/tensorflow/python/trackable) apparently, and they discouraged the use of `pickle`. I would say we can add the `<2.14.0` in the requirements, and perhaps think of not using `pickle` in the future.

@itrharrison I can edit the requirements, if you agree?

**Comment by itrharrison** [comment]
Yup, sounds good!

**Comment by dpiras** [comment]
Just FYI, I bypassed this problem with a simple script that can be run once to convert the `.pkl` file to a `NumPy` dictionary, and then make `CosmoPower-JAX` usable even with `TF>=2.14`. If needed, we can probably adapt the same thing for `CosmoPower`, depending on how you upload your model. Feel free to reopen this issue if you'd need to use `TF>=2.14`, and we can look into it.

**Comment by borisbolliet** [comment]
FYI I made a script here: 

https://github.com/cosmopower-organization/convert_pkl2npz

and converted all our previous emulators into npz, so they should readily be used in @HTJense updated version.  

I used @dpiras script. 

Thanks!
