### ISSUE TITLE
tensorflow_probability version requirement < 0.22

### ISSUE THREAD

**Issue by mattyowl** [alessiospuriomancini/cosmopower#24]
Hi,

The latest version of tensorflow_probability does not seem to be compatible. However, version 0.21.0 is working. So, as well as having tensorflow < 2.14 as a requirement, this should be also I think.

Cheers
Matt

**Comment by dpiras** [comment]
Hi Matt! Thank you for raising this. Could you please let me know which version of TFP is not working?

**Comment by mattyowl** [comment]
Hmm. I replied to this at the time by email but it doesn't show up here. Anyway:

 0.22.1 (and I assume 0.22.0 as well), i.e., the latest version on PyPI.

Can't remember the exception, sorry, but pretty sure it's just API changes in tensorflow_probability.

**Comment by alessiospuriomancini** [comment]
Thank you, now implemented in #25
