### ISSUE TITLE
Derived parameters

### ISSUE THREAD

**Issue by nnedelko** [alessiospuriomancini/cosmopower#30]
Hi! I am working on a HMC/NUTS extension of MontePython, so I need a differentiable code that is able to interpolate not just the spectra from CLASS/CAMB, but also the derived parameters such as rs_drag or sigma_8. Is it possible to modify CosmoPower to train it to predict these? Basically I want the prediction string to contain a set of derived parameters instead of the spectral modes. Creating the training data seems straightforward enough, but what parts of the training process do I need to modify?

**Comment by nnedelko** [comment]
Thank you! Just a small clarification: 2405.07903 mentions the CAMB/CLASS interfacing framework would be included in a CosmoPower release. Is that still in-progress or am I just not looking in the right place?

**Comment by alessiospuriomancini** [comment]
still in progress, but will be here on this repo very soon!

**Comment by nnedelko** [comment]
Ah ok, thank you, I'll keep an eye out for it!
