### ISSUE TITLE
Conda Forge package

### ISSUE THREAD

**Issue by joezuntz** [alessiospuriomancini/cosmopower#31]
Hi all,

It would be useful to CosmoPower available within conda-forge so other packages can depend on it.

I'll do this now. Please let me know if you'd like one of the devs to be a maintainer on it.

Cheers,
Joe

**Comment by alessiospuriomancini** [comment]
thanks @joezuntz , please put me down as a maintainer. I'm observing https://github.com/conda-forge/staged-recipes/pull/28296

**Comment by joezuntz** [comment]
Just added you as a maintainer - can you comment on that PR to say that you're happy to be one? They require that.

**Comment by alessiospuriomancini** [comment]
linux/osx/win builds are all successful now, is it worth adding an empty commit to trigger the linter checks again?

**Comment by alessiospuriomancini** [comment]
thanks @joezuntz, I have added the conda installation instructions to the README
