### ISSUE TITLE
Problem with ell_range 

### ISSUE THREAD

**Issue by Eminencetoosure** [alessiospuriomancini/cosmopower#8]
Hello alessio, 
Please i am working on cosmosis, i took some time to understand your cosmosis pipeline and the code itself. but i have a problem with how you generate "ell_range".  can you please help me further on understanding the (ell_range = training_features["mode"]). 
![Uploading Screenshot 2022-07-24 at 17.10.34.png…]()

**Comment by Eminencetoosure** [comment]
if you can explained to me better how you get the tt log_spectral

**Comment by alessiospuriomancini** [comment]
Hi @Eminencetoosure , the `ell_range` is the range of multipoles at which you compute your CMB power spectrum, or the Fourier modes at which you compute the matter power spectrum. Note the typo `mode --> modes`, it should not be `ell_range = training_features["mode"]`, it should be `ell_range = training_features["modes"]`. The `log_spectra` are the logarithm of the power spectra computed by the Boltzmann code, which CosmoPower emulates.
